

eureka:
  client:
    register-with-eureka: false
server:
  port: 8222
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: keycloak_admin_client
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/users/**
        - id: task_service
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/groups/**