

eureka:
  client:
    register-with-eureka: true
server:
  port: 8222
  server:
    servlet:
      context-path: /
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: keycloak_admin_client
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/users/**
        - id: task_service
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/groups/**
#  profiles:
#    active:
#      - ${ACTIVE_SPRING_PROFILE:dev}

springdoc:
  enable-native-support: true
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    urls:
      - url: /v3/api-docs
        name: API Gateway Service
        primaryName: API Gateway Service
      - url: /keycloak-admin-client/v3/api-docs
        name: Keycloak Admin Client
        primaryName: Users Service
#      - url: /task-service/v3/api-docs
#        name: Task Service
#        primaryName: Task Service


        #When you want to disable swagger UI based on profiles,
         # can use following properties in respective environment.
        #  For an example to disable logs in production environment.
#spring:
#  config:
#    activate:
#      on-profile: prod
#
#springdoc:
#  swagger-ui:
#    enabled: false
#  api-docs:,
#    enabled: false