





eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:1111/auth/realms/mini-project-spring
          jwk-set-uri: http://localhost:1111/auth/realms/mini-project-spring/protocol/openid-connect/certs

server:
  servlet:
    context-path: /
  port: 8081
keycloak:
  realm: mini-project-spring
  resource: app-user
  auth-server-url: http://localhost:1111/auth/ #docker container
  credentials:
    username: 'admin'
    password: 'admin'
    client-id: 'app-user'
    secret: '9CGz4anfkrRxZQd6qzl4CErRBGaDbuvH'
    provider: secret

openapi:
  oAuthFlow:
    tokenUrl=http://localhost:1111/auth/realms/mini-project-spring/protocol/openid-connect/token
#  service:
#    title: keycloak-admin-client #title that you will want to display in the swagger ui
#    version: 1.0.0
#    url: http://localhost:8222 #api gateway url
#springdoc:
#  api-docs:
#    path: /keycloak-admin-client/v3/api-docs #these urls will used to load the swagger ui of this service by the api gateway
#  swagger-ui:
#    path: /keycloak-admin-client/swagger-ui.html

logging:
  level:
    org.springframework.web: debug

management:
  tracing:
    sampling:
      probability: 1.0
