spring:
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: http://localhost:1111/auth/realms/mini-project-spring
          jwk-set-uri: http://localhost:1111/auth/realms/mini-project-spring/protocol/openid-connect/certs

  datasource:
    url: jdbc:postgresql://localhost:5432/test
    username: postgres
    password: 123
  jpa:
    database: POSTGRESQL
    hibernate.ddl-auto: update

server:
  port: 8082

keycloak:
  realm: mini-project-spring
  resource: app-user
  auth-server-url: http://localhost:1111/auth
  credentials:
    username: 'admin'
    password: 'admin'
    client-id: 'app-user'
    secret: '9CGz4anfkrRxZQd6qzl4CErRBGaDbuvH'
    provider: secret
management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
resilience4j:
  circuitbreaker:
    instances:
      task:
        registerHealthIndicator: true
        event-consumer-buffer-size: 10
        failure-rate-threshold: 50
        minimum-number-of-calls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        wait-duration-in-open-state: 5s
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-size: 10
        sliding-window-type: COUNT_BASED